Merge scripts into one

diff --git a/scripts/rzbackup b/scripts/rzbackup
--- a/scripts/rzbackup
+++ b/scripts/rzbackup
@@ -1,11 +1,9 @@
 #!/bin/bash -e
 set -e
 
-# Backups are not allowed to change anything
-# results in 400 permissions where even owner
-# can't change files
-
-umask 0277
+# Set default permissions on newly created files so that only owner has
+# read/write access and nobody else, results in 500 permissions
+umask 0177
 
 # Timestamp, the date/time we started
 start_time=$(date +"%Y-%m-%d-%H-%M")
@@ -15,18 +13,13 @@ hostname="`/bin/hostname`"
 domainname=`/bin/hostname | /bin/sed -n 's/[^.]*\.//p' | /bin/sed -n 's/.$//p' || /bin/dnsdomainname 2> /dev/null`
 
 # Constants
+verbosity=1
 default_password_file='/etc/zbackup.pwd'
 default_source_dir='/'
 default_remote_user=$hostname
-default_remote_host="backup.${domainname}"
+default_remote_host="backup${domainname}"
 default_remote_dir="/home/${hostname}"
-
-# Variables
-password_file=$default_password_file
-source_dir=$default_source_dir
-remote_user=$default_remote_user
-remote_host=$default_remote_host
-remote_dir=$default_remote_dir
+default_backup_secret="`/usr/bin/pwgen -s -1 32`"
 
 # Color Constants
 black='\e[0;30m'
@@ -41,15 +34,98 @@ white='\e[0;37m'
 blank='\e[0m' # No Color
 
 # Colored echo
-# takes color and message as parameters, valid colors are listed in the constants section
+# takes color and message as parameters,
+# valid colors are listed in the constants section
+# also prints all messages to the syslog daemon for non-attended runs
 function color_echo {
         eval color=\$$1
-        /bin/echo -e "${color}${2}${blank}"
-        /usr/bin/logger "zbackup: ${2}"
+        echo -e "${color}${2}${blank}"
+        /usr/bin/logger "rzbackup: ${2}"
 }
 
-# Log start
-color_echo "Started at ${start_time}"
+# Debug method for verbose debugging
+function debug {
+	if [ ${verbosity} -ge $1 ]; then
+		color_echo yellow "${@:2}"
+	fi
+}
+
+# Function to print the help message
+print_usage()
+{
+cat << EOF
+usage: $0 options
+
+Provides easy to use scripts to install, backup and restore using zbackup over SSH
+
+MODES:
+    install  Installs required packages and initializes a zbackup repository on a remote host via SSH
+    backup   Backs up a directory or file to a remote host via SSH
+    restore  Restores a backup from a remote host via SSH
+
+OPTIONS:
+   -h    Show this message
+   -v    Verbose debug logging
+EOF
+}
+
+# Parse command line arguments
+while getopts ":vh" opt; do
+	case ${opt} in
+		'h')
+			print_usage
+			exit 0
+		;;
+		'v')
+			verbosity=10
+			color_echo cyan "Verbosity set to ${verbosity}"
+		;;
+		'?')
+			color_echo red "Invalid option $OPTARG"
+			print_usage
+			exit 64
+		;;
+		':')
+			color_echo red "Missing option argument for option $OPTARG"
+			print_usage
+			exit 64
+		;;
+		'*')
+			color_echo red "Unknown error while processing options"
+			print_usage
+			exit 64
+		;;
+	esac
+done
+
+# When parameter handling gets added make sure the secret can't be entered as a
+# parameter but only via a prompt to protect the password
+
+# Variables
+password_file=$default_password_file
+source_dir=$default_source_dir
+remote_user=$default_remote_user
+remote_host=$default_remote_host
+remote_dir=$default_remote_dir
+backup_secret=$default_packup_secret
+release="`uname -r`"
+flavour="`echo ${release} | awk -F\. '{print substr ($4,0,2)}'`"
+major_version="`echo ${release} | awk -F\. '{print substr ($4,3,3)}'`"
+platform="`uname -m`"
+osfamily='Unknown'
+apt-get help > /dev/null 2>&1 && osfamily='Debian'
+yum help help > /dev/null 2>&1 && osfamily='RedHat'
+
+
+# Exit on failure function, takes error message as parameter
+function exit_on_fail {
+    color_echo red "${1}" >&2
+    debug 10 "[$( caller )] $*"
+    debug 10 "BASH_SOURCE: ${BASH_SOURCE[*]}"
+    debug 10 "BASH_LINENO: ${BASH_LINENO[*]}"
+    debug 10  "FUNCNAME: ${FUNCNAME[*]}"
+    exit 1
+}
 
 # Traps for cleaning up on exit
 # Originally from http://www.linuxjournal.com/content/use-bash-trap-statement-cleanup-temporary-files
@@ -57,9 +133,9 @@ declare -a on_sig_items
 
 function on_exit()
 {
-    color_echo magenta "Received SIGEXIT, Cleaning up: $i"
+    debug 2 "Received SIGEXIT, Cleaning up: $i"
     for i in "${on_sig_items[@]}"; do
-	debug 10 "Executing cleanup statement: $i"
+	debug 2 "Executing cleanup statement: $i"
       	eval $i
     done
 }
@@ -83,42 +159,186 @@ function add_on_sig()
     fi
 }
 
-# Verify password file exists
-if ! [ -f ${password_file} ] ; then
-    color_echo red "Password file not found, make  sure ${password_file} exists and is readable by the backup process"
-fi
+function install()
+{
+    # Check if we have root permissions or if sudo is available
+    if [ $EUID -ne 0 ]; then
+            exit_on_fail "This script needs to be run as root or with sudo"
+    fi
 
-# Verify password file permissions are correct and warn if they are not
-if [ "`/usr/bin/stat -c %a ${password_file}`" != '600' ] ; then
-    color_echo red "Warning, file permissions on ${password_file} are not 600 (-rw-------) as they should be!"
-fi
+    # Install method depends on OS family
+    color_echo cyan "Detected OS based on: ${osfamily}"
+    case "${osfamily}" in
+        RedHat)
+            wget -qO - "http://dl.fedoraproject.org/pub/epel/6/${platform}/epel-release-6-8.noarch.rpm" | sudo rpm -Uhv - || exit_on_fail "Unable to add the EPEL repository to YUM, please add it manually"
+            # Could use a repo to fall back to for getting the package
+            yum --enablerepo=epel -y install fuse-sshfs zbackup pwgen || exit_on_fail "Unable to install requried packages fuse-sshfs, zbackup and pwgen, please install them manually"
+        ;;
+        Debian)
+            apt-get update
+            if ! apt-cache show zbackup; then
+                color_echo green "Adding ppa:jarl/zbackup apt repository"
+                sudo add-apt-repository ppa:jarl/zbackup || exit_on_fail "Unable to add zbackup apt repository, please add it manually"
+                apt-get update
+            fi
+            color_echo green "Installing zbackup and sshfs"
+            apt-get install zbackup sshfs pwgen || exit_on_fail "Unabel to install the zbackup, sshfs and pwgen packages, please install them manually"
+        ;;
+        *) color_echo red "Unknown Operating System, can't continue" && exit 1;;
+    esac
 
-# Create secure temporary directory for mount point
-tmp_dir="`/bin/mktemp -d`"
+    # Verify password file exists, if not then we create one and tell the user
+    if ! [ -f "${password_file}" ] ; then
+        color_echo green "No password file found, creating ${password_file}"
+        echo "${backup_secret}" > "${password_file}" || "Unable to write password file ${password_file}!"
+        color_echo magenta "Created password file with secret: ${backup_secret}"
+        color_echo magenta "Please store this secret or the file somewhere safe, without it you will not be able to restore any backups"
+    fi
 
-# Set signal handler to clean up directory on signal/exit but only if it's
-# empty as it should be if unmount was successful
-add_on_sig rmdir ${tmp_dir}
+    # Create secure temporary directory for mount point
+    tmp_dir="`/bin/mktemp -d`" || exit_on_fail "Unable to create temporary directory"
 
-# Mount fuse sshfs filesystem
-# Automaticaly unmount ssh fuse filesystem on signal/exit
-/usr/bin/sshfs ${remote_user}@${remote_host}:${remote_dir} ${tmp_dir} && add_on_Sig /bin/fusermount -u ${tmp_dir}
+    # Mount fuse sshfs filesystem
+    /usr/bin/sshfs "${remote_user}@${remote_host}:${remote_dir}" "${tmp_dir}" || exit_on_fail "Mounting remote filesystem failed, please verify your SSH settings and confirm you have set up SSH keys, see README for details!"
 
-# Verify zbackup structure exists in remote/target directory
-if ! [ -d "${tmp_dir}/backups" ] && [ -d "${tmp_dir}/bundles" ] && [ -d "${tmp_dir}/index" ] && [ -f "${tmp_dir}/info" ]; then
-    color_echo red "zbackup structure does not exist on remote host or is damaged, if this is a fresh installatation consider running the install command to create the structure!"
-    exit -1
-fi
+    # Set signal handler to automaticaly unmount ssh fuse filesystem on signal/exit
+    add_on_sig /bin/fusermount -u "${tmp_dir}"
 
-# Runt the backup, time the execution
-backup_result="`/usr/bin/time /bin/tar c --exclude={'/proc/*','/sys/*','/tmp/*','/dev/*','/mnt*','/media','/root/*','/selinux/*'} ${source_dir} | /usr/bin/zbackup backup ${tmp_dir}/backups/${hostname}-${start_time} --password-file ${password_file}`"
+    # Set signal handler to clean up directory on signal/exit but only if it's
+    # empty as it should be if unmount was successful
+    add_on_sig /bin/rmdir "${tmp_dir}"
 
-# Timestamp, the date/time we finished
-end_time=$(date +"%Y-%m-%d-%H-%M")
+    # Create zbackup structure in remote/target directory
+    if ! [ -d "${tmp_dir}/backups" ] && ! [ -d "${tmp_dir}/bundles" ] && ! [ -d "${tmp_dir}/index" ] && ! [ -f "${tmp_dir}/info" ]; then
+        color_echo green "creating remote zbackup structure"
+        /usr/bin/zbackup init "${tmp_dir}" --password-file /etc/zbackup.pwd || exit_on_fail "Unable to initialize new zbackup storage"
+    else
+        color_echo red "zbackup structure found in target directory, will not overwrite, exiting!"
+        exit -1
+    fi
 
-# Log results
-color_echo green "Completed successfully at ${end_time}"
-color_echo green  $backup_result
+    color_echo green "Successfully installed and configured zbackup"
+}
+
+function backup()
+{
+    # Log start
+    color_echo green "Started at ${start_time}"
+    # Verify password file exists
+    if ! [ -f ${password_file} ] ; then
+        color_echo red "Password file not found, make  sure ${password_file} exists and is readable by the backup process"
+    fi
+
+    # Verify password file permissions are correct and warn if they are not
+    if [ "`/usr/bin/stat -c %a ${password_file}`" != '600' ] ; then
+        color_echo red "Warning, file permissions on ${password_file} are not 600 (-rw-------) as they should be!"
+    fi
+
+    # Create secure temporary directory for mount point
+    tmp_dir="`/bin/mktemp -d`"
+
+    # Set signal handler to clean up directory on signal/exit but only if it's
+    # empty as it should be if unmount was successful
+    add_on_sig rmdir ${tmp_dir}
+
+    # Mount fuse sshfs filesystem
+    # Automaticaly unmount ssh fuse filesystem on signal/exit
+    /usr/bin/sshfs ${remote_user}@${remote_host}:${remote_dir} ${tmp_dir} || exit_on_fail "Failed to mount remote SSH volume: ${remote_user}@${remote_host}:${remote_dir} on ${tmp_dir}"
+    add_on_sig /bin/fusermount -u ${tmp_dir}
+
+    # Verify zbackup structure exists in remote/target directory
+    if ! [ -d "${tmp_dir}/backups" ] && [ -d "${tmp_dir}/bundles" ] && [ -d "${tmp_dir}/index" ] && [ -f "${tmp_dir}/info" ]; then
+        exit_on_fail "zbackup structure does not exist on remote host or is damaged, if this is a fresh installatation consider running the install command to create the structure!"
+    fi
+
+    # Runt the backup, time the execution
+    backup_result="`/usr/bin/time /bin/tar c --exclude={'/proc/*','/sys/*','/tmp/*','/dev/*','/mnt*','/media','/root/*','/selinux/*'} ${source_dir} | /usr/bin/zbackup backup ${tmp_dir}/backups/${hostname}-${start_time} --password-file ${password_file}`" || exit_on_fail "Unable to back up ${source_dir} to ${remote_user}@${remote_host}:${remote_dir} using password from ${password_file}"
+
+    # Timestamp, the date/time we finished
+    end_time=$(date +"%Y-%m-%d-%H-%M")
+
+    # Log results
+    color_echo green "Completed successfully at ${end_time}"
+    color_echo green  $backup_result
+}
+
+function restore()
+{
+    # Verify password file exists, if not then we create one and ask user for
+    # the secret
+
+    if ! [ -f ${password_file} ] ; then
+        color_echo green "No password file found, creating ${password_file}"
+        read -p "Please enter the shared secret(password) to access backups and perform restore:"
+        echo "${REPLY}" > "${password_file}"
+        color_echo magenta "Created password file with secret: ${backup_secret}"
+    fi
+
+    # Verify zbackup and sshfs are installed, if not we run install
+    if ! [ -f '/usr/bin/sshfs' ] && [ -f '/usr/bin/zbackup' ]; then
+        `/bin/pwd`/rzinstall
+    fi
+
+    # Create secure temporary directory for mount point
+    tmp_dir="`/bin/mktemp -d`"
+
+    # Set signal handler to clean up directory on signal/exit but only if it's
+    # empty as it should be if unmount was successful
+    add_on_sig rmdir ${tmp_dir}
+
+    # Mount fuse sshfs filesystem
+    # Automaticaly unmount ssh fuse filesystem on signal/exit
+    /usr/bin/sshfs ${remote_user}@${remote_host}:${remote_dir} ${tmp_dir} && add_on_Sig /bin/fusermount -u ${tmp_dir}
+
+    # Verify zbackup structure exists in remote/target directory
+    if ! [ -d "${tmp_dir}/backups" ] && [ -d "${tmp_dir}/bundles" ] && [ -d "${tmp_dir}/index" ] && [ -f "${tmp_dir}/info" ]; then
+        color_echo red "zbackup structure does not exist on remote host or is damaged, try running zbackup manually!"
+        exit -1
+    fi
+
+    # Run the restore
+    cd "${source_dir}"
+    /usr/bin/zbackup restore --password-file "${password_file}" "${tmp_dir}/backups/${hostname}-${start_time}" | /bin/tar -vx
+
+    # Timestamp, the date/time we finished
+    end_time=$(date +"%Y-%m-%d-%H-%M")
+
+    # Log results
+    color_echo green "Backup restore completed successfully at ${end_time}"
+
+    # Verify password file permissions are correct and warn if they are not
+    if [ "`/usr/bin/stat -c %a ${password_file}`" != '600' ] ; then
+        color_echo red "Warning, file permissions on ${password_file} are not 600 (-rw-------) as they should be!"
+    fi
+}
+
+# "Main" function
+# Copy argument list to arguments variable
+arguments=${@}
+for argument in ${arguments}; do
+    # Parse arguments in a safe way
+    case ${argument} in
+        install)
+                install
+        ;;
+        backup)
+                echo running backup
+                backup
+        ;;
+        restore)
+                restore
+        ;;
+        -*)
+            # Ignore flags, handled by getopts
+            debug 10 "Ignored flag ${argument}"
+        ;;
+        *)
+            color_echo red "Unknown argument ${argument}"
+            print_usage
+            exit 64
+        ;;
+   esac
+done
 
 # Exit gracefully, triggering cleanup including unmount and removal of
 # temporary directory
