Fix exclution rules

diff --git a/scripts/rzbackup b/scripts/rzbackup
--- a/scripts/rzbackup
+++ b/scripts/rzbackup
@@ -235,7 +235,7 @@ function add_on_sig()
     fi
 }
 
-# Converts relative paths to full paths,ignores invalid paths,
+# Converts relative paths to full paths, ignores invalid paths,
 finalize_path()
 {
         eval path=\$$1
@@ -363,7 +363,7 @@ function install()
     if ! [ -f "${password_file}" ] ; then
         backup_secret="`pwgen -s -1 32`"
         color_echo green "No password file found, creating ${password_file}"
-        echo "${backup_secret}" | sudo tee "${password_file}" || "Unable to write password file ${password_file}!"
+        echo "${backup_secret}" | tee "${password_file}" || "Unable to write password file ${password_file}!"
         color_echo magenta "Created password file with secret: ${backup_secret}"
         color_echo magenta "Please store this secret or the file somewhere safe, without it you will not be able to restore any backups"
         color_echo magenta "In addition to storing this secret you should also store the private SSH key (id_rsa/id_dsa) in a safe place if your server does not allow password logins for restore purposes"
@@ -441,7 +441,7 @@ function backup()
     # Run the backup, be really nice so we don't slow down the system
     # Preserve permissions
     # Handle sparse files like lastlog correctly
-    nice -n 19 tar cp -S --exclude={'./proc','./sys','./tmp','./dev','./mnt','./media','./selinux'} -C ${source_dir} . | pv -ptrb | /usr/bin/zbackup backup ${tmp_dir}/backups/${hostname}-${start_time} --password-file ${password_file} || exit_on_fail "Unable to back up ${source_dir} to ${remote_user}@${remote_host}:${remote_dir} using password from ${password_file}"
+    nice -n 19 tar cp -S --exclude={'proc','sys','tmp','dev','mnt','media','selinux'} -C ${source_dir} . | pv -ptrb | /usr/bin/zbackup backup ${tmp_dir}/backups/${hostname}-${start_time} --password-file ${password_file} || exit_on_fail "Unable to back up ${source_dir} to ${remote_user}@${remote_host}:${remote_dir} using password from ${password_file}"
 
     # Timestamp, the date/time we finished
     end_time=$(date +"%Y-%m-%d-%H-%M-%S")
